# Generated by Django 5.0.9 on 2026-09-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='e.g. CHEST_PAIN, BURN, BLEEDING, UNCONSCIOUS, CHOKING', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('instruction', models.TextField()),
            ],
            options={
                'ordering': ['category', 'step_number'],
                'unique_together': {('category', 'step_number')},
            },
        ),
    ]
