# Generated by Django 5.0.9 on 2026-09-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialization', models.CharField(choices=[('EMERGENCY_MEDICINE', 'Emergency Medicine'), ('CARDIOLOGY', 'Cardiology'), ('GENERAL', 'General / Emergency Support')], default='GENERAL', max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
